TochalTools/Models/MarketerViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TochalTools.Models
{
    public class MarketerListViewModel
    {
        public int Id { get; set; }
        public int TrackingCode { get; set; }
        public string Name { get; set; }
        public string Tell { get; set; }
        public string Age { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public bool IsArchived { get; set; }
        public string Date { get; set; }
    }
    public class MarketerCreateViewModel
    {
        [Display(Name = "نام و نام خانوادگی *")]
        [Required(ErrorMessage = "لطفا نام و نام خانوادگی خود را وارد نمایید.")]
        public string Name { get; set; }
        [Display(Name = "شماره تماس *")]
        [Required(ErrorMessage = "لطفا شماره تماس خود را وارد نمایید.")]
        public string Tell { get; set; }
        [Display(Name = "سن *")]
        [Required(ErrorMessage = "لطفا سن خود را وارد نمایید.")]
        public string Age { get; set; }
        [Display(Name = "کشور *")]
        [Required(ErrorMessage = "لطفا کشور را انتخاب نمایید.")]
        public int CountryId { get; set; }
        [Display(Name = "استان *")]
        [Required(ErrorMessage = "لطفا استان را انتخاب نمایید.")]
        public int StateId { get; set; }
        [Display(Name = "شهر *")]
        [Required(ErrorMessage = "لطفا شهر را انتخاب نمایید.")]
        public int CityId { get; set; }
        [Display(Name = "آدرس *")]
        [Required(ErrorMessage = "لطفا آدرس محل سکونت خود را وارد نمایید.")]
        public string Address { get; set; }
        [Display(Name = "توضیح کوتاه")]
        public string Description { get; set; }
        public List<SelectListItem> CountriesList { get; set; }
    }

    public class MarketerDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tell { get; set; }
        public string Age { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public int TrackingCode { get; set; }
        public string Date { get; set; }
    }
}

TochalTools/Controllers/MarketerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TochalTools.Models;
using TochalTools.Services;

namespace TochalTools.Controllers
{
    [Authorize(Roles = "Developer,SuperAdministrator,Marketer")]
    public class MarketerController : Controller
    {
        MarketerService marketerService = new MarketerService();
        public async Task<ActionResult> List(string id)
        {
            ViewBag.Id = id;
            return View(await marketerService.ReadAll(id));
        }

        public async Task<ActionResult> Details(int id)
        {
            var model = await marketerService.ReadById(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Print(int id)
        {
            var model = await marketerService.ReadById(id, true);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Create()
        {
            AddressService addressService = new AddressService();
            MarketerCreateViewModel viewModel = new MarketerCreateViewModel
            {
                CountriesList = await addressService.ReadAllCountriesForSelect()
            };
            return View(viewModel);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name,Tell,Age,CountryId,StateId,CityId,Address,Description")] MarketerCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var trackingCode = await marketerService.Create(viewModel);
                if (trackingCode > 0)
                {
                    return RedirectToAction("Print", new { id = trackingCode});
                }
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<JsonResult> Archive(int id)
        {
            return Json(await marketerService.Archive(id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            return Json(await marketerService.Delete(id), JsonRequestBehavior.AllowGet);
        }
    }
}

TochalTools/Views/Marketer/Create.cshtml
@model MarketerCreateViewModel
@{
    ViewBag.Title = "ثبت نام در همکاری فروش";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!-- contact area -->
<div class="section-full content-inner bg-white">
    <div class="container">
        <div class="row">
            <!-- Left part start -->
            <div class="col-lg-12">
                <div class="p-a30 bg-gray clearfix m-b30 ">
                    <h2>اطلاعات خود را وارد نمایید.</h2>
                    <div class="dzFormMsg"></div>
                    @using (Html.BeginForm("Create", "Marketer", FormMethod.Post))
                    {
                        var name = "";
                        var mobile = "";
                        var tell = "";
                        var address = "";
                        var countryId = 0;
                        var stateId = 0;
                        var cityId = 0;
                        if (User.Identity.IsAuthenticated)
                        {
                            ApplicationDbContext db = new ApplicationDbContext();
                            var profile = db.Profiles.Find(User.Identity.GetUserId());
                            if (profile != null)
                            {
                                if (profile.Name != null && profile.Name != "")
                                {
                                    name = profile.Name;
                                }
                                if (profile.Mobile != null && profile.Mobile != "")
                                {
                                    mobile = profile.Mobile;
                                }
                                else if (profile.Tell != null && profile.Tell != "")
                                {
                                    mobile = profile.Tell;
                                }
                                if (profile.Address != null && profile.Address != "")
                                {
                                    address = profile.Address;
                                }
                                if (profile.CountryId > 0)
                                {
                                    countryId = profile.CountryId;
                                }
                                if (profile.StateId > 0)
                                {
                                    stateId = profile.StateId;
                                }
                                if (profile.CityId > 0)
                                {
                                    cityId = profile.CityId;
                                }
                            }
                        }
                        <script>
                            var countryId = '@countryId';
                            var stateId = '@stateId';
                            var cityId = '@cityId';
                            var address = '@address'
                        </script>
                        @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>نام و نام خانوادگی <span class="required">*</span> @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })</label>
                                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", @Value = name } })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>شماره تماس <span class="required">*</span> @Html.ValidationMessageFor(m => m.Tell, "", new { @class = "text-danger" })</label>
                                @Html.EditorFor(m => m.Tell, new { htmlAttributes = new { @class = "form-control", @Value = mobile } })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>سن <span class="required">*</span> @Html.ValidationMessageFor(m => m.Age, "", new { @class = "text-danger" })</label>
                                @Html.EditorFor(m => m.Age, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>توضیح کوتاه @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })</label>
                                @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @rows = "3" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>کشور <span class="required">*</span> @Html.ValidationMessageFor(m => m.CountryId, "", new { @class = "text-danger" })</label>
                                @Html.DropDownListFor(m => m.CountryId, Model.CountriesList, "انتخاب کنید", new { @class = "form-control", @onchange = "getStates('CountryId', 'StateId', 'CityId')" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>استان <span class="required">*</span> @Html.ValidationMessageFor(m => m.StateId, "", new { @class = "text-danger" })</label>
                                @Html.DropDownListFor(m => m.StateId, new List<SelectListItem>(), "انتخاب کنید", new { @class = "form-control", @onchange = "getCities('StateId', 'CityId')" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>شهر <span class="required">*</span> @Html.ValidationMessageFor(m => m.CityId, "", new { @class = "text-danger" })</label>
                                @Html.DropDownListFor(m => m.CityId, new List<SelectListItem>(), "انتخاب کنید", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="comment-form-author">
                                <label>آدرس <span class="required">*</span> @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })</label>
                                @Html.TextAreaFor(m => m.Address, new { @class = "form-control", @rows = "6" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12" id="messagediv">
                        <button type="submit" value="Submit" class="site-button "> <span>ثبت نام</span> </button>
                    </div>
                </div>
                    }
                </div>
            </div>
            <!-- Left part END -->
        </div>
    </div>
</div>
<!-- contact area  END -->
@section bottomScripts {
    <script src="/Content/Layouts/AdminLayout/assets/js/pages/address.js"></script>
    <script>
        if (countryId != null && countryId > 0) {
            $('#CountryId').val(countryId);
            $.ajax({
                type: 'Post',
                url: '/Address/ReadAllStatesByCountryIdForSelect',
                data: { id: countryId },
                success: function (data) {
                    data.forEach(function (item) {
                        $('#StateId').append('<option value="' + item.Value + '">' + item.Text + '</option>');
                    });
                    $('#StateId').removeAttr('disabled');
                    $('#CityId').removeAttr('disabled');
                    if (stateId != null && stateId > 0) {
                        $('#StateId').val(stateId);
                        $.ajax({
                            type: 'Post',
                            url: '/Address/ReadAllCitiesByStateIdForSelect',
                            data: { id: stateId },
                            success: function (data) {
                                data.forEach(function (item) {
                                    $('#CityId').append('<option value="' + item.Value + '">' + item.Text + '</option>');
                                });
                                $('#CityId').removeAttr('disabled');
                                if (cityId != null && cityId > 0) {
                                    $('#CityId').val(cityId);
                                }
                            }
                        });
                    }
                }
            });
        }
        if (address != null && address != '') {
            $('#Address').val(address);
        }
    </script>
}

TochalTools/Views/Marketer/Details.cshtml
@model MarketerDetailsViewModel
@{
    ViewBag.Title = "جزئیات بازاریاب";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>جزئیات بازاریاب انتخاب شده</small>
                </h3>
            </div>


        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="user-profile">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="profile-img-style">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="media-body">
                                    <label style="font-size:14px;">شماره پیگیری: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.TrackingCode</span></label>
                                </div>
                            </div>
                            <hr />
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">نام و نام خانوادگی: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Name</span></label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">شماره تماس: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Tell</span></label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">سن: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Age</span></label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">تاریخ ثبت: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Date</span></label>
                                </div>
                            </div>
                            <hr />
                            <div class="col-sm-12">
                                <div class="media-body">
                                    <label style="font-size:14px;">توضیح کوتاه: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Description</span></label>
                                </div>
                            </div>
                            <hr />
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">کشور: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.CountryName</span></label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">استان: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.StateName</span></label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="media-body">
                                    <label style="font-size:14px;">شهر: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.CityName</span></label>
                                </div>
                            </div>
                            <hr />
                            <div class="col-sm-12">
                                <div class="media-body">
                                    <label style="font-size:14px;">آدرس: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Address</span></label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Marketer/List.cshtml
@model List<MarketerListViewModel>
@{
    var type = "";
    if (ViewBag.Id != null && ViewBag.Id != "")
    {
        if (ViewBag.Id.ToLower() == "archived")
        {
            type = " - آرشیو شده";
        }
    }
    ViewBag.Title = "لیست بازاریابان" + type;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>لیست بازاریابان ثبت شده</small>
                </h3>
            </div>
            <div class="col-lg-6">
                <a href="/Marketer/List/Archived" class="btn btn-primary btn-link">لیست آرشیو</a>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <!--Zero Configuration  Starts -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="basic-1" class="display dataTable cell-border">
                            <thead>
                                <tr>
                                    <th>شماره پیگیری</th>
                                    <th>نام و نام خانوادگی</th>
                                    <th>شماره تماس</th>
                                    <th>سن</th>
                                    <th>کشور</th>
                                    <th>استان</th>
                                    <th>شهر</th>
                                    <th>تاریخ</th>
                                    <th>مدیریت</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {

                                    <tr id="marketer-@item.Id">
                                        <td>@item.TrackingCode</td>
                                        <td>@item.Name</td>
                                        <td>@item.Tell</td>
                                        <td>@item.Age</td>
                                        <td>@item.CountryName</td>
                                        <td>@item.StateName</td>
                                        <td>@item.CityName</td>
                                        <td>@item.Date</td>
                                        <td>
                                            <a href="/Marketer/Details/@item.Id" target="_blank" class="btn btn-info btn-datatable">مشاهده</a>
                                            <button type="button" onclick="deleteMarketer('@item.Id', 'بازاریاب')" class="btn btn-danger btn-datatable">حذف</button>
                                            @if (!item.IsArchived)
                                            {
                                                <button type="button" onclick="archiveMarketer('@item.Id', 'بازاریاب')" class="btn btn-primary btn-datatable">آرشیو</button>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!--Zero Configuration  Ends -->
    </div>
</div>
@section bottomScripts{
    <script>
        function deleteMarketer(address, title) {
            swal({
                title: 'آیا از حذف ' + title + ' مطمئن هستید؟',
                text: title + ' حذف خواهد شد و قابل بازگردانی نخواهد بود.',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'Post',
                        url: '/Marketer/Delete',
                        data: { id: address },
                        success: function (data) {
                            if (data == true) {
                                swal(title + ' با موفقیت حذف شد!', {
                                    icon: 'success',
                                });
                                $('#marketer-' + address).fadeOut(1000);
                            }
                            else {
                                swal(title + ' حذف نشد!');
                            }
                        }
                    });
                }
            });
        }
        function archiveMarketer(address, title) {
            swal({
                title: 'آیا از آرشیو ' + title + ' مطمئن هستید؟',
                text: title + ' آرشیو خواهد شد.',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'Post',
                        url: '/Marketer/Archive',
                        data: { id: address },
                        success: function (data) {
                            if (data == true) {
                                swal(title + ' با موفقیت آرشیو شد!', {
                                    icon: 'success',
                                });
                                $('#marketer-' + address).fadeOut(1000);
                            }
                            else {
                                swal(title + ' آرشیو نشد!');
                            }
                        }
                    });
                }
            });
        }
    </script>
}

TochalTools/Views/Marketer/Print.cshtml
@model MarketerDetailsViewModel
@{
    ViewBag.Title = "جزئیات ثبت نام";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!-- contact area -->
<div class="section-full content-inner bg-white contact-style-1">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="p-a30 m-b30 border-1 contact-area align-self-stretch">
                    <h2 class="m-b10">@ViewBag.Title</h2>
                    <p>اطلاعات وارد شده خود را در این قسمت مشاهده نمایید.</p>
                    <div class="row">
                        <hr />
                        <div class="col-sm-12">
                            <div class="media-body">
                                <label style="font-size:14px;">شماره پیگیری: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.TrackingCode</span></label>
                            </div>
                        </div>
                        <hr />
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">نام و نام خانوادگی: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Name</span></label>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">شماره تماس: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Tell</span></label>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">سن: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Age</span></label>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">تاریخ ثبت: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Date</span></label>
                            </div>
                        </div>
                        <hr />
                        <div class="col-sm-12">
                            <div class="media-body">
                                <label style="font-size:14px;">توضیح کوتاه: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Description</span></label>
                            </div>
                        </div>
                        <hr />
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">کشور: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.CountryName</span></label>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">استان: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.StateName</span></label>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="media-body">
                                <label style="font-size:14px;">شهر: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.CityName</span></label>
                            </div>
                        </div>
                        <hr />
                        <div class="col-sm-12">
                            <div class="media-body">
                                <label style="font-size:14px;">آدرس: <span style="font-size:14px;font-weight:600;padding-right:5px;">@Model.Address</span></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>