TochalTools/Models/AddressViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TochalTools.Models
{
    public class CountryListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class CountryCreateViewModel
    {
        [Required(ErrorMessage = "لطفا نام کشور را وارد نمایید.")]
        [Display(Name = "نام کشور *")]
        public string Name { get; set; }
    }

    public class CountryEditViewModel
    {
        [Display(Name = "شناسه")]
        public int Id { get; set; }
        [Required(ErrorMessage = "لطفا نام کشور را وارد نمایید.")]
        [Display(Name = "نام کشور *")]
        public string Name { get; set; }
    }

    public class StateListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class StateListPageViewModel
    {
        public List<StateListViewModel> States { get; set; }
        public string CountryName { get; set; }
    }

    public class StateCreateViewModel
    {
        [Required(ErrorMessage = "لطفا نام استان را وارد نمایید.")]
        [Display(Name = "نام استان *")]
        public string Name { get; set; }
        [Display(Name = "شناسه کشور")]
        public int CountryId { get; set; }
    }

    public class StateEditViewModel
    {
        [Display(Name = "شناسه")]
        public int Id { get; set; }
        [Required(ErrorMessage = "لطفا نام استان را وارد نمایید.")]
        [Display(Name = "نام استان *")]
        public string Name { get; set; }
        [Display(Name = "شناسه کشور")]
        public int CountryId { get; set; }
    }

    public class CityListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class CityListPageViewModel
    {
        public List<CityListViewModel> Cities { get; set; }
        public string StateName { get; set; }
    }

    public class CityCreateViewModel
    {
        [Required(ErrorMessage = "لطفا نام شهر را وارد نمایید.")]
        [Display(Name = "نام شهر *")]
        public string Name { get; set; }
        [Display(Name = "شناسه استان")]
        public int StateId { get; set; }
    }

    public class CityEditViewModel
    {
        [Display(Name = "شناسه")]
        public int Id { get; set; }
        [Required(ErrorMessage = "لطفا نام شهر را وارد نمایید.")]
        [Display(Name = "نام شهر *")]
        public string Name { get; set; }
        [Display(Name = "شناسه استان")]
        public int StateId { get; set; }
    }

}

TochalTools/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TochalTools.Classes;
using TochalTools.Models;
using TochalTools.Services;

namespace TochalTools.Controllers
{
    [Authorize(Roles = "Developer,SuperAdministrator")]
    public class AddressController : Controller
    {
        AddressService addressService = new AddressService();

        public async Task<ActionResult> CountryList()
        {
            return View(await addressService.ReadAllCountries());
        }

        public ActionResult CreateCountry()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCountry([Bind(Include = "Name")] CountryCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await addressService.CreateCountry(viewModel);
            }
            return RedirectToAction("CountryList");
        }

        public async Task<ActionResult> EditCountry(int id)
        {
            return View(await addressService.ReadCountryByIdForEdit(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditCountry([Bind(Include = "Id,Name")] CountryEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await addressService.EditCountry(viewModel);
            }
            return RedirectToAction("CountryList");
        }

        [HttpPost]
        public async Task<JsonResult> DeleteCountry(int id)
        {
            return Json(await addressService.DeleteCountry(id), JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> StateList(int id)
        {
            ViewBag.CountryId = id;
            return View(await addressService.ReadAllStatesByCountryId(id));
        }

        public ActionResult CreateState(int id)
        {
            ViewBag.CountryId = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateState([Bind(Include = "Name,CountryId")] StateCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await addressService.CreateState(viewModel);
            }
            return RedirectToAction("StateList", new { id = viewModel.CountryId});
        }

        public async Task<ActionResult> EditState(int id)
        {
            return View(await addressService.ReadStateByIdForEdit(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditState([Bind(Include = "Id,Name,CountryId")] StateEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await addressService.EditState(viewModel);
            }
            return RedirectToAction("StateList", new { id = viewModel.CountryId });
        }

        [HttpPost]
        public async Task<JsonResult> DeleteState(int id)
        {
            return Json(await addressService.DeleteState(id), JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> CityList(int id, int countryId)
        {
            ViewBag.StateId = id;
            ViewBag.CountryId = countryId;
            return View(await addressService.ReadAllCitiesByStateId(id));
        }

        public ActionResult CreateCity(int id, int countryId)
        {
            ViewBag.StateId = id;
            ViewBag.CountryId = countryId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCity([Bind(Include = "Name,StateId")] CityCreateViewModel viewModel, int countryId)
        {
            if (ModelState.IsValid)
            {
                await addressService.CreateCity(viewModel);
            }
            return RedirectToAction("CityList", new { id = viewModel.StateId, countryId = countryId });
        }

        public async Task<ActionResult> EditCity(int id, int countryId)
        {
            ViewBag.CountryId = countryId;
            return View(await addressService.ReadCityByIdForEdit(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditCity([Bind(Include = "Id,Name,StateId")] CityEditViewModel viewModel, int countryId)
        {
            if (ModelState.IsValid)
            {
                await addressService.EditCity(viewModel);
            }
            return RedirectToAction("CityList", new { id = viewModel.StateId, countryId = countryId });
        }

        [HttpPost]
        public async Task<JsonResult> DeleteCity(int id)
        {
            return Json(await addressService.DeleteCity(id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> ReadAllCountriesForSelect()
        {
            return Json(await addressService.ReadAllCountriesForSelect(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> ReadAllStatesByCountryIdForSelect(int id)
        {
            return Json(await addressService.ReadAllStatesByCountryIdForSelect(id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> ReadAllCitiesByStateIdForSelect(int id)
        {
            return Json(await addressService.ReadAllCitiesByStateIdForSelect(id), JsonRequestBehavior.AllowGet);
        }
    }
}

TochalTools/Views/Address/CityList.cshtml
@model CityListPageViewModel
@{
    ViewBag.Title = "لیست شهرهای " + Model.StateName;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>لیست شهرهای ثبت شده</small>
                </h3>
            </div>
            <div class="col-lg-6">
                <a href="/Address/StateList/@ViewBag.CountryId" class="btn btn-primary btn-link"><i class="icon-arrow-right"></i></a>
                <a href="/Address/CreateCity/@ViewBag.StateId/@ViewBag.CountryId" class="btn btn-secondary btn-link">شهر جدید</a>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <!--Zero Configuration  Starts -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="basic-1" class="display dataTable cell-border">
                            <thead>
                                <tr>
                                    <th>نام شهر</th>
                                    <th>مدیریت</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model.Cities)
                                {
                                    <tr id="city-@item.Id">
                                        <td>@item.Name</td>
                                        <td>
                                            <a href="/Address/EditCity/@item.Id/@ViewBag.CountryId" class="btn btn-success btn-datatable">ویرایش</a>
                                            <button type="button" onclick="deleteCity('@item.Id', 'شهر')" class="btn btn-danger btn-datatable">حذف</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!--Zero Configuration  Ends -->
    </div>
</div>
@section bottomScripts {
    <script src="/Content/Layouts/AdminLayout/assets/js/pages/address-list.js"></script>
}

TochalTools/Views/Address/CountryList.cshtml
@model IEnumerable<CountryListViewModel>
@{
    ViewBag.Title = "لیست کشورها";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>لیست کشورهای ثبت شده</small>
                </h3>
            </div>
            <div class="col-lg-6">
                <a href="/Address/CreateCountry" class="btn btn-secondary btn-link">کشور جدید</a>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <!--Zero Configuration  Starts -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="basic-1" class="display dataTable cell-border">
                            <thead>
                                <tr>
                                    <th>نام کشور</th>
                                    <th>مدیریت</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="country-@item.Id">
                                        <td>@item.Name</td>
                                        <td>
                                            <a href="/Address/EditCountry/@item.Id" class="btn btn-success btn-datatable">ویرایش</a>
                                            <button type="button" onclick="deleteCountry('@item.Id', 'کشور')" class="btn btn-danger btn-datatable">حذف</button>
                                            <a href="/Address/StateList/@item.Id" class="btn btn-info btn-datatable">استان ها</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!--Zero Configuration  Ends -->
    </div>
</div>
@section bottomScripts {
    <script src="/Content/Layouts/AdminLayout/assets/js/pages/address-list.js"></script>
}

TochalTools/Views/Address/CreateCity.cshtml
@model CityCreateViewModel
@{
    ViewBag.Title = "شهر جدید";
    Layout = "/Views/Shared/_AdminLayout.cshtml";
    int countryId = ViewBag.CountryId;
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>ایجاد شهر جدید</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="row">
                <div class="col-sm-12">
                    @using (Html.BeginForm("CreateCity", "Address", FormMethod.Post, new { @class = "theme-form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.StateId, new { @Value = ViewBag.StateId })
                        @Html.Hidden("countryId", countryId)
                        <div class="card">
                            <div class="card-header">
                                <h5>مشخصات شهر</h5>
                                <span>اطلاعات شهر را در این قسمت وارد نمایید.</span>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Name, new { @class = "col-form-label pt-0" })
                                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control input-air-primary" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-div">
                            <button type="submit" class="btn btn-success">ایجاد</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Address/CreateCountry.cshtml
@model CountryCreateViewModel
@{
    ViewBag.Title = "کشور جدید";
    Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>ایجاد کشور جدید</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="row">
                <div class="col-sm-12">
                    @using (Html.BeginForm("CreateCountry", "Address", FormMethod.Post, new { @class = "theme-form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="card">
                            <div class="card-header">
                                <h5>مشخصات کشور</h5>
                                <span>اطلاعات کشور را در این قسمت وارد نمایید.</span>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Name, new { @class = "col-form-label pt-0" })
                                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control input-air-primary" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-div">
                            <button type="submit" class="btn btn-success">ایجاد</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Address/CreateState.cshtml
@model StateCreateViewModel
@{
    ViewBag.Title = "استان جدید";
    Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>ایجاد استان جدید</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="row">
                <div class="col-sm-12">
                    @using (Html.BeginForm("CreateState", "Address", FormMethod.Post, new { @class = "theme-form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.CountryId, new { @Value = ViewBag.CountryId })
                        <div class="card">
                            <div class="card-header">
                                <h5>مشخصات استان</h5>
                                <span>اطلاعات استان را در این قسمت وارد نمایید.</span>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Name, new { @class = "col-form-label pt-0" })
                                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control input-air-primary" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-div">
                            <button type="submit" class="btn btn-success">ایجاد</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Address/EditCity.cshtml
@model CityEditViewModel
@{
    ViewBag.Title = "ویرایش شهر";
    Layout = "/Views/Shared/_AdminLayout.cshtml";
    int countryId = ViewBag.CountryId;
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>ویرایش شهر انتخابی</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="row">
                <div class="col-sm-12">
                    @using (Html.BeginForm("EditCity", "Address", FormMethod.Post, new { @class = "theme-form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.Id)
                        @Html.HiddenFor(m => m.StateId)
                        @Html.Hidden("countryId", countryId)
                        <div class="card">
                            <div class="card-header">
                                <h5>مشخصات شهر</h5>
                                <span>اطلاعات شهر را در این قسمت وارد نمایید.</span>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Name, new { @class = "col-form-label pt-0" })
                                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control input-air-primary" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-div">
                            <button type="submit" class="btn btn-success">ویرایش</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Address/EditCountry.cshtml
@model CountryEditViewModel
@{
    ViewBag.Title = "ویرایش کشور";
    Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>ویرایش کشور انتخابی</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="row">
                <div class="col-sm-12">
                    @using (Html.BeginForm("EditCountry", "Address", FormMethod.Post, new { @class = "theme-form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.Id)
                        <div class="card">
                            <div class="card-header">
                                <h5>مشخصات کشور</h5>
                                <span>اطلاعات کشور را در این قسمت وارد نمایید.</span>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Name, new { @class = "col-form-label pt-0" })
                                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control input-air-primary" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-div">
                            <button type="submit" class="btn btn-success">ویرایش</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Address/EditState.cshtml
@model StateEditViewModel
@{
    ViewBag.Title = "ویرایش استان";
    Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>ویرایش استان انتخابی</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="row">
                <div class="col-sm-12">
                    @using (Html.BeginForm("EditState", "Address", FormMethod.Post, new { @class = "theme-form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.Id)
                        @Html.HiddenFor(m => m.CountryId)
                        <div class="card">
                            <div class="card-header">
                                <h5>مشخصات استان</h5>
                                <span>اطلاعات استان را در این قسمت وارد نمایید.</span>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Name, new { @class = "col-form-label pt-0" })
                                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control input-air-primary" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-div">
                            <button type="submit" class="btn btn-success">ویرایش</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TochalTools/Views/Address/StateList.cshtml
@model StateListPageViewModel
@{
    ViewBag.Title = "لیست استان های " + Model.CountryName;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    @ViewBag.Title
                    <small>لیست استان های ثبت شده</small>
                </h3>
            </div>
            <div class="col-lg-6">
                <a href="/Address/CountryList" class="btn btn-primary btn-link"><i class="icon-arrow-right"></i></a>
                <a href="/Address/CreateState/@ViewBag.CountryId" class="btn btn-secondary btn-link">استان جدید</a>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<div class="container-fluid">
    <div class="row">
        <!--Zero Configuration  Starts -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="basic-1" class="display dataTable cell-border">
                            <thead>
                                <tr>
                                    <th>نام استان</th>
                                    <th>مدیریت</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model.States)
                                {
                                    <tr id="state-@item.Id">
                                        <td>@item.Name</td>
                                        <td>
                                            <a href="/Address/EditState/@item.Id" class="btn btn-success btn-datatable">ویرایش</a>
                                            <button type="button" onclick="deleteState('@item.Id', 'استان')" class="btn btn-danger btn-datatable">حذف</button>
                                            <a href="/Address/CityList/@item.Id/@ViewBag.CountryId" class="btn btn-info btn-datatable">شهر ها</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!--Zero Configuration  Ends -->
    </div>
</div>
@section bottomScripts {
    <script src="/Content/Layouts/AdminLayout/assets/js/pages/address-list.js"></script>
}